services:
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    networks:
      - web
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - web
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=notSecureChangeMe
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      args:
        BACKEND_URL: https://sportfest.casparkroll.de
    restart: always
    ports:
      - 3000:80
    networks:
      - web
      - proxy
    environment:
      - API_PORT=80
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=notSecureChangeMe
      - DB_NAME=tournament
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      # Route incoming traffic for the domain to this container
      - "traefik.http.routers.sportfest-web.rule=Host(`sportfest.casparkroll.de`)"
      - "traefik.http.routers.sportfest-web.entrypoints=websecure"
      - "traefik.http.routers.sportfest-web.tls=true"
      # Explicitly tell Traefik which port your container listens on internally
      - "traefik.http.services.sportfest-web.loadbalancer.server.port=80"
networks:
  proxy:
    external: true
  web:
